name: Deploy to VPS

on:
  push:
    branches: ["test-ci"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Pull latest image"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/game-server:latest
            
            echo "Stop old container"
            docker stop game-server || true
            docker rm game-server || true
            
            echo "Run new container"
            docker run -d \
              --name game-server \
              -p 8989:8989 \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/game-server:latest
            
            echo "Deployment done!"