name: Deploy to VPS (TEST-CICD)

on:
  push:
    branches: ["test-cicd"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Pull TEST-CICD image"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/game-server:test-cicd
            
            echo "Stop old container"
            docker stop game-server-test || true
            docker rm game-server-test || true
            
            echo "Run new TEST-CICD container"
            docker run -d \
              --name game-server-test \
              -p 8989:8989 \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/game-server:test-cicd
            
            echo "Deployment done!"