name: Build and Push Docker Image (TEST-CICD)

on:
  push:
    branches: ["test-cicd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create config.properties
        run: |
          cat <<EOF > src/main/resources/config.properties
          db.host=${{ secrets.DB_HOST }}
          db.port=${{ secrets.DB_PORT }}
          db.username=${{ secrets.DB_USERNAME }}
          db.password=${{ secrets.DB_PASSWORD }}
          db.dbname=${{ secrets.DB_NAME }}
          db.driver=${{ secrets.DB_DRIVER }}
          EOF
          
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image for test-cicd
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/game-server:test-cicd .

      - name: Push image for test-cicd
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/game-server:test-cicd
